### ISSUE TITLE
Support UNICODE

### ISSUE THREAD

**Issue by phaedron** [wolverdude/GenSON#47] opened 2020-02-26 21:09 UTC
I have a JSON file in UTF-8. Genson seems to choke on UNICODE encoded files.

**Comment by wolverdude** [comment] 2020-04-11 18:54
I'll try to reproduce. Can you give me more information? It's best if you can include the file and tell me which version of Python you're using.

**Comment by aloneunix** [comment] 2020-05-13 12:17
argparse seems to be using default open() which uses locale.getpreferredencoding() to determine system's locale encoding. In my case it was cp1252 and json is UTF-8 with Cyrillic symbols in it.

I guess it's either need to force to open files in utf8 encoding (`argparse.FileType('r', encoding='utf8')`) or to add an option to specify encoding as argument.

You can reproduce it with following JSON:
`{"test": "тест"}`

**Comment by phaedron** [comment] 2020-05-13 18:18
attached is a json file from an SAP HANA system which uses a UNICODE code page.
[calc_scenario.json.txt](https://github.com/wolverdude/GenSON/files/4623831/calc_scenario.json.txt)

**Comment by wolverdude** [comment] 2020-05-17 10:31
@phaedron did you close this intentionally? It seems to still be an issue.

**Comment by phaedron** [comment] 2020-05-18 15:24
I don't remember closing this. If you have cycles to address it, seems like it would be useful as UNICODE support would be needed.

**Comment by emanb29** [comment] 2020-08-14 18:34
For Windows users having this issue (as Windows' default locale is cp1252), use the stdin fallback with a PYTHONIOENCODING override.
Example using git bash:
`export PYTHONIOENCODING=UTF-8; cat myobj1.json myobj2.json | genson`

**Comment by wolverdude** [comment] 2020-08-14 20:29
It seems like the best way to solve this problem is just to add an encoding option to the executable. How does that sound?

**Comment by phaedron** [comment] 2020-08-14 20:33
sounds fine. Allows the user to explicitly specify what the encoding should be.

**Comment by wolverdude** [comment] 2020-08-14 20:43
Will it be sufficient if the option applies to all listed files? I feel like it could make the interface much more complex to do otherwise. If you need to merge files with multiple different encodings, you can either convert the files beforehand or just write a Python script for it.

**Comment by emanb29** [comment] 2020-08-14 21:01
That would be my expectation @wolverdude. I can't imagine using differently-encoded JSON files for the same schema.

**Comment by wolverdude** [comment] 2020-08-15 21:44
I've updated the code, and it should be fixed in the next release by adding an `--encoding` option to the CLI tool.

However, it will only be fixed for Python 3 users as Python 2 doesn't allow setting encoding on `argparse.FileType` objects. If you have installed it as a Python 2 package, you will not see the `--encoding` option or be able to use it unless you upgrade to Python 3.

**Closed** 2020-08-15 22:46 UTC
Labels: bug

**Comment by ololoe** [comment] 2022-05-17 17:55
Sorry, but it's not fixed at all. Why do you need encoding parameter for valid JSON? It's always UTF-8 according to standard.

**Comment by ololoe** [comment] 2022-05-17 17:56
```
Traceback (most recent call last):
  File "c:\users\user\appdata\local\programs\python\python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\user\appdata\local\programs\python\python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\User\AppData\Local\Programs\Python\Python39\Scripts\genson.exe\__main__.py", line 7, in <module>
  File "c:\users\user\appdata\local\programs\python\python39\lib\site-packages\genson\cli.py", line 9, in main
    CLI().run()
  File "c:\users\user\appdata\local\programs\python\python39\lib\site-packages\genson\cli.py", line 22, in run
    self.add_objects()
  File "c:\users\user\appdata\local\programs\python\python39\lib\site-packages\genson\cli.py", line 32, in add_objects
    self._call_with_json_from_fp(self.builder.add_object, fp)
  File "c:\users\user\appdata\local\programs\python\python39\lib\site-packages\genson\cli.py", line 124, in _call_with_json_from_fp
    for json_string in self._get_json_strings(fp.read().strip()):
  File "c:\users\user\appdata\local\programs\python\python39\lib\encodings\cp1251.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x98 in position 12454: character maps to <undefined>

```
Why are you using local encoding cp1251?

**Comment by wolverdude** [comment] 2022-05-18 06:59
@ololoe Are you experiencing this issue? If so, could you include some information to reproduce it?
